DROP TABLE IF EXISTS recipes CASCADE;

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  directions TEXT[]
);

DROP TABLE IF EXISTS logs;

CREATE TABLE logs (
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  date_of_event TEXT NOT NULL,
  notes TEXT NOT NULL,
  rating INT NOT NULL,
  recipe_id BIGINT REFERENCES recipes(id)
);
